version: '2.4'

services:
  www:
    build: ./www
    ports:
      - 8080:80 # if you change your local port update public/script.js:1273
    volumes:
      - ./www/public:/usr/share/nginx/html:ro

  app:
    build: ./app
    entrypoint: ["/app/shhgit", "--live=http://www/push"]
    depends_on:
      - www
    volumes:
      - ./app/config.yaml:/app/config.yaml:ro
      - ./app/rules:/app/rules:ro